<a href="https://colab.research.google.com/github/77jackm/Bourke-Pytorch-Tutorial/blob/main/Copy_of_00_MyPyTorch_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

print ("This is my Pytorch Tutorial")

2.3.0+cu121
This is my Pytorch Tutorial


###Introduction to Tensors
Creating Tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get Python Tensor value back as an Int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# The number of dimensions of a tensor can be determined by inspection.
# Just look at the number of square bracket [] it has
vector.ndim

1

In [ ]:
# The item() method returns a single int value. Since a vector
# has 2 values you need to select which item in the vector
vector[1].item()

7

In [ ]:
vector.tolist()
vector.shape

[7, 7]

In [ ]:
# Find the shape of the vector.
# Shape indicates the number of dimensions and the number of elements in each dimension
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX  = torch.tensor([[7,8],
                        [8,9],
                        [10,11]])
MATRIX

tensor([[ 7,  8],
        [ 8,  9],
        [10, 11]])

In [ ]:
MATRIX.ndim

2

In [ ]:

MATRIX.shape

torch.Size([3, 2])

In [ ]:
# MATRIX
MATRIX  = torch.tensor([[[7,8],
                        [8,9]],
                        [[10,11],
                         [12,13]]])
MATRIX

tensor([[[ 7,  8],
         [ 8,  9]],

        [[10, 11],
         [12, 13]]])

In [ ]:
MATRIX.ndim


3

In [ ]:
MATRIX.shape

torch.Size([2, 2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                       ]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
TENSOR[0,0,1]

tensor(2)

In [ ]:
#PRACTICE

#Create a tensor or order (2,3,5)

TENSOR1 = torch.tensor([[[0,1,2,3,4],
                         [5,6,7,8,9],
                         [10,11,12,13,14]],
                        [[15,16,17,18,19],
                         [20,21,22,23,24],
                         [25,26,27,28,29]]])
TENSOR1

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

In [ ]:
TENSOR1.ndim

3

In [ ]:
TENSOR1.shape

torch.Size([2, 3, 5])

In [ ]:
TENSOR1[1,0,2].item()


17

In [ ]:
TENSOR1[1,0,]

tensor([15, 16, 17, 18, 19])

In [ ]:
# How to print each element of a tensor. Start with highest dimension and go down the hierarchy
for plane in TENSOR1:
  for row in plane:
    for column_element in row:
      print (column_element)

tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)
tensor(10)
tensor(11)
tensor(12)
tensor(13)
tensor(14)
tensor(15)
tensor(16)
tensor(17)
tensor(18)
tensor(19)
tensor(20)
tensor(21)
tensor(22)
tensor(23)
tensor(24)
tensor(25)
tensor(26)
tensor(27)
tensor(28)
tensor(29)


In [ ]:
#Float32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #Tensor datatype
                               device=None, #Device then tensor is on cpu or gpu
                               requires_grad=False) #Whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype


torch.float32

The 3 common error with PyTorch and ML
1. Using the wrong datatype or mixed datatypes
2. Tensors not the right shape (ie. Matrix Multiplication requires compatible shapes)
3. Allocating the tensor to the wrong device. Tensors in an operation have to be on same device

In [ ]:
#To change data type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
output_tensor = float_32_tensor * float_16_tensor
output_tensor.dtype

torch.float32

In [ ]:
#Information we want to regularly get from our tensors
TENSOR1.dtype
TENSOR1.shape
TENSOR1.device


torch.int64

torch.Size([2, 3, 5])

device(type='cpu')

In [ ]:
#Create a tensor with random elements
some_tensor = torch.rand(3,4)
some_tensor


tensor([[0.9839, 0.6343, 0.5182, 0.9815],
        [0.8008, 0.8768, 0.1616, 0.1061],
        [0.4010, 0.1090, 0.6921, 0.3937]])

In [ ]:
# Find the details of the tensor created
some_tensor
print (f"some_tensor has datatype: {some_tensor.dtype}")
print (f"some_tensor has shape: {some_tensor.shape}")
print (f"some_tensor is on device: {some_tensor.device}")



tensor([[0.9839, 0.6343, 0.5182, 0.9815],
        [0.8008, 0.8768, 0.1616, 0.1061],
        [0.4010, 0.1090, 0.6921, 0.3937]])

some_tensor has datatype: torch.float32
some_tensor has shape: torch.Size([3, 4])
some_tensor is on device: cpu


### Manipulating Tensors (Tensor Operations)**

Tensor Operations Include:
* Addition
* Substraction
* Multiplication (Element Wise)
* Division
* Matrix multiplication

In [ ]:
#Create a Tensor and add a scalar to each element
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10 from a tensor
tensor - 10


tensor([-9, -8, -7])

In [ ]:
#There are also built-in Torch functions for these operations

torch.mul(tensor, 10)


tensor([10, 20, 30])

### MATRIX MULTIPLICATION

There are two mail rules of performing matrix multiplication in NN and DL

1. Scalar Multiplication: Element-wise multiplication
2. Matrix Multiplication: DOT PRODUCT (The most common operation in ANN)

Two requirements have meet for Matrix Multiplication:
1. A x B = C
Dimensions of matrices are such that A = m x n.    B = n x p.     C = n x p
the inner dimension "n" must match
2. The resulting matrix has the shape (dimensions) of outer dimension m x p

We can use tensor.shape to ensure that rule #1 is satisfied

In [ ]:
# Element-Wise Multiplication
print (tensor, "*", tensor)
print (f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

Let's have a gazer is Australian for lets have a look

In [ ]:
#Let's do the matrix multiplication by hand and time it
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print (value)

tensor(14)
CPU times: user 3.34 ms, sys: 1.97 ms, total: 5.31 ms
Wall time: 6.09 ms


In [ ]:
%%time
output = torch.matmul(tensor, tensor)
print (output)
# You can also use @ sign instead of matmul
tensor @ tensor

tensor(14)
CPU times: user 2.11 ms, sys: 971 µs, total: 3.08 ms
Wall time: 2.79 ms


tensor(14)

###Shapes for MAtrix Multiplication

In [ ]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
#torch.mm( tensor_A, tensor_B) #torch.mm is the same as torch.matmul
n1 = tensor_A.shape
n2 = tensor_B.shape
if n1[0] != n2[1]:
  print("Error: The inner dimensions must match")
#



Error: The inner dimensions must match


In [ ]:
# To fix the error in this case we can manipulate the shape of one tensor using transpose
# A transpose switches the axes or dimensions of a given tensor

tensor_B
tensor_B.T # transpose
torch.mm(tensor_A, tensor_B.T)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

tensor([[ 7,  8,  9],
        [10, 11, 12]])

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
#Now transpose first tensor to see if we get the same result: Absolutely not. You don't
#evn have to compute it just look at the outer dimensions to see the size of the output
#tensor which 2x2 instead of 3x3
torch.mm(tensor_A.T, tensor_B)


tensor([[ 76, 103],
        [100, 136]])

##Tensor Aggregation: Find the min, max, mean, sum, etc
Called aggregation because reducing a multiple dimensional tensor into a scalaraero

In [ ]:
#Create a tensor with a range of 100 and step of 10
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#Find the mean
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#Let's see the datatype arange created
x.dtype

torch.int64

In [ ]:
#It's double precision float and mean wants single precision float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Find the sum of a tensor
torch.sum(x), x.sum()
# Either style is fine


(tensor(450), tensor(450))

### Find the Positional Location where these Aggregates occur


In [ ]:
#Find the location of the max using argmax,
#Useful in SoftMax Activation Function calculation
print (f"Max value of X is at index:",torch.argmax(x))
print (f"Max value of X is:",x[torch.argmax(x)])

Max value of X is at index: tensor(9)
Max value of X is: tensor(90)


In [ ]:
#Find the location of min using argmin
print (f"Min value of X is at index:",torch.argmin(x))
print (f"Min value of X is:",x[torch.argmin(x)])

Min value of X is at index: tensor(0)
Min value of X is: tensor(0)


### Reshaping, Stacking, Squeezing and Unsqueezing Tensors
* Reshaping: Changes the dimensions (shape) of a tensor to new defined shape
* View: Return a view of an input tensor of certain shape but use the same memory as original tensor
* Stacking: Stack multiple tensors on top of each other in any dimension (vstack is a special function for vertical) or similar to vstack side-by-side (hstack)
* Squeeze:  Removes a dimension of "1" from a target tensor
* Unsqueeze: Adds a dimension of "1" to a target
* Permute: Returns a view of the input with dimensions permuted (swapped) in a specified manner

In [ ]:
x = torch.arange(1,101,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x = torch.arange(start = 1.,end = 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# The initial tensor must have sufficient elements to create the reshaped tensor
x = torch.reshape(x, (9,1))
x

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x = torch.arange(1,11,1)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = torch.reshape( x, (1,2,5))
x, x.shape

(tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]),
 torch.Size([1, 2, 5]))

In [ ]:
#Change the view. Changing z changes x because they share the same memory
z = x.view(1,9)
z,  z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Z declared to be a view of X is a pointer to X tensor. So if Z is changed then X changes

In [ ]:
z[:,0]= 0.5
z, x

(tensor([[0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000]]),
 tensor([0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000]))

### STACKING TENSORS


In [ ]:
# Stack Tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000]])

In [ ]:
#Stack Tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [2.0000, 2.0000, 2.0000, 2.0000],
        [3.0000, 3.0000, 3.0000, 3.0000],
        [4.0000, 4.0000, 4.0000, 4.0000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [6.0000, 6.0000, 6.0000, 6.0000],
        [7.0000, 7.0000, 7.0000, 7.0000],
        [8.0000, 8.0000, 8.0000, 8.0000],
        [9.0000, 9.0000, 9.0000, 9.0000]])

In [ ]:
x_vstacked = torch.vstack([x,x,x,x])
x_vstacked

tensor([[0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000]])

In [ ]:
x_hstacked = torch.hstack([x,x,x,x])
x_hstacked

tensor([0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000,
        0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000,
        0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000,
        0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000])

In [ ]:
x.shape
x.reshape(1,1,9)
x.shape


torch.Size([9])

tensor([[[0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000,
          9.0000]]])

torch.Size([9])

In [ ]:
#Squeeze the tensor: remove all dimensions =1
x.squeeze().shape


torch.Size([9])

In [ ]:
x = torch.squeeze(x)
x.shape
x

torch.Size([2, 5])

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [ ]:
# Note how unsqueezing adds one dimention at the location specified in "dim"
x = torch.unsqueeze(x, dim =3)
x.shape, x

(torch.Size([1, 2, 5, 1]),
 tensor([[[[ 1],
           [ 2],
           [ 3],
           [ 4],
           [ 5]],
 
          [[ 6],
           [ 7],
           [ 8],
           [ 9],
           [10]]]]))

In [ ]:
shape = (2,3,4,5) # 2 volumes, 3 planes ea, 4 rows, 5 colums
x = torch.rand(shape)
x

tensor([[[[0.5520, 0.6825, 0.7769, 0.9218, 0.5108],
          [0.2313, 0.7962, 0.3952, 0.3686, 0.0157],
          [0.0913, 0.7596, 0.5869, 0.1310, 0.8788],
          [0.6177, 0.3767, 0.5937, 0.4577, 0.0249]],

         [[0.2815, 0.6006, 0.3203, 0.7489, 0.8626],
          [0.1603, 0.5197, 0.9791, 0.5299, 0.3749],
          [0.3845, 0.2587, 0.3284, 0.5820, 0.2596],
          [0.0058, 0.1046, 0.2394, 0.2081, 0.4300]],

         [[0.2086, 0.7971, 0.0532, 0.0953, 0.7196],
          [0.8831, 0.4754, 0.6267, 0.7833, 0.1276],
          [0.3537, 0.5724, 0.9079, 0.4654, 0.0278],
          [0.0173, 0.3268, 0.2477, 0.4142, 0.6079]]],


        [[[0.2447, 0.1266, 0.6585, 0.3272, 0.3346],
          [0.5679, 0.8273, 0.6012, 0.6810, 0.7612],
          [0.8438, 0.3448, 0.4627, 0.3317, 0.5930],
          [0.8932, 0.1139, 0.5700, 0.4343, 0.1535]],

         [[0.5632, 0.4756, 0.3516, 0.7186, 0.8335],
          [0.3127, 0.2278, 0.3127, 0.0260, 0.8612],
          [0.0023, 0.3677, 0.2028, 0.8438, 0.0896],
  

In [ ]:
y = torch.randint(0,10,shape)
y, shape

(tensor([[[[4, 0, 2, 3, 3],
           [0, 5, 0, 9, 6],
           [5, 6, 9, 3, 4],
           [1, 9, 7, 1, 3]],
 
          [[1, 6, 4, 9, 7],
           [6, 3, 4, 4, 5],
           [0, 6, 5, 4, 2],
           [6, 9, 9, 1, 4]],
 
          [[5, 6, 3, 3, 5],
           [0, 7, 5, 9, 0],
           [7, 6, 9, 0, 9],
           [6, 2, 2, 6, 2]]],
 
 
         [[[5, 7, 4, 8, 8],
           [3, 6, 3, 0, 8],
           [9, 7, 9, 7, 7],
           [7, 1, 9, 7, 3]],
 
          [[2, 0, 9, 5, 7],
           [9, 3, 8, 8, 1],
           [3, 8, 2, 8, 7],
           [7, 4, 5, 4, 9]],
 
          [[4, 4, 2, 4, 9],
           [1, 4, 6, 9, 6],
           [9, 9, 1, 4, 5],
           [5, 7, 8, 3, 4]]]]),
 (2, 3, 4, 5))

### PERMUTING TENSORS

Permutting rearranges the elements of a tensor to the dimensions of the permutation requestes i.e. size(2,3,5) to size(5,2,3)
The input is the new order of dimensions i.e. (0,1,2) to (2,0,1). A permute is a view
Permutations of tensors are used often in Image Processing (Computer Vision)

In [ ]:
x = torch.randn(2,3,5)
x.shape, x
x= torch.permute(x, (2,0,1))
x.shape, x

(torch.Size([2, 3, 5]),
 tensor([[[-1.7659,  0.3218, -1.3755, -0.8567,  1.8455],
          [ 0.4126,  0.1700, -0.5447,  2.1054,  0.5803],
          [ 0.0791, -0.5101, -2.1290,  1.8234,  0.8956]],
 
         [[ 0.2142,  0.6879,  1.7817, -1.3025,  1.3441],
          [ 0.4300,  0.1203, -0.5078, -0.0806, -1.2784],
          [-0.3381,  1.0017, -1.5547,  0.3098, -0.2481]]]))

(torch.Size([5, 2, 3]),
 tensor([[[-1.7659,  0.4126,  0.0791],
          [ 0.2142,  0.4300, -0.3381]],
 
         [[ 0.3218,  0.1700, -0.5101],
          [ 0.6879,  0.1203,  1.0017]],
 
         [[-1.3755, -0.5447, -2.1290],
          [ 1.7817, -0.5078, -1.5547]],
 
         [[-0.8567,  2.1054,  1.8234],
          [-1.3025, -0.0806,  0.3098]],
 
         [[ 1.8455,  0.5803,  0.8956],
          [ 1.3441, -1.2784, -0.2481]]]))

### Indexing (selecting specific data from tensors)
Indexing with Pytorch is similar to indexing with NumPy

In [ ]:
#Create a tensor
import torch
# arange() to create the tensor is executed before reshape()
# arange returns a 1x9 tensor and reshape converts it to a 1x3x3
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index on new tensor on 1st bracket (dim=0)
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on middle (2nd) bracket (dim =1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Let's index on the third index (dim =2)
x[0][0][0]
# Remember, the first index is plane, the second one the row and third the column
# you can use a ":" to target all of a target dimension

tensor(1)

In [ ]:
# Ex: target the 9
x[0][2][2], x[0,2,2]

(tensor(9), tensor(9))

In [ ]:
#Get all element of 0th and 1st dimension but only one of dim=3
x[:, :, 1]

tensor([[2, 5, 8]])

#### Pytorch Tensors & Numpy
Numpy is a popular scientific Python numerical computing library
Pytorch has integration with NumPY
* Data in Numpy can be converted to Pytorch tensor -> torch.from_numpy(ndarray)
* Pytorch tensor to Numpy ndarray -> torch.Tensor.numpy()


In [ ]:
#Numpy array to tensor
import torch
import numpy as np
#the default datatype in Numpy is float 64 and in Pytorch float32 so ...
array = np.arange(1.0, 8.0, dtype=np.float32)
array, array.dtype
#or you can use tensor = torch.from_numpy(array).dtype(torch.float32)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.], dtype=float32),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#### In both cases the tensor and the array are two differente vars in memory

####Reproducibility (trying to take randomness out of random)
The way ML works is it starts with a model full of parameters with random values and the algorithm updates these random values making them better representations of the data in an iterative process

However if we are trying to do reproducible experiments we would like to reproduce the initial random numbers.

To reduce the randomness in Pytorch use the concept of a **Random Seed**

In [ ]:
torch.rand(3,3)

tensor([[0.0573, 0.1251, 0.1105],
        [0.3821, 0.3484, 0.6104],
        [0.2101, 0.5042, 0.7867]])

In [ ]:
torch.rand(3,3)

tensor([[0.0841, 0.2909, 0.4819],
        [0.0714, 0.7961, 0.4944],
        [0.1183, 0.4365, 0.7689]])

In [ ]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4970, 0.5200, 0.6733, 0.0342],
        [0.8025, 0.4400, 0.7174, 0.7506],
        [0.3855, 0.6751, 0.1251, 0.6951]])
tensor([[0.7532, 0.8232, 0.6537, 0.2052],
        [0.2587, 0.8553, 0.6979, 0.0761],
        [0.6211, 0.4691, 0.2745, 0.2404]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Create random but reproducible tensors Notice you need 3 lines of code
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
# Must set the RANDOM_SEED each time
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Random Seed is also called Manual Seed in Pytorch.
https://pythor.org/docs/stable/notes/randomness.html
https://en.wikipedia.org/wiki/Random_seed

## Running Tensors & Pytorch Objects on GPUs

In [ ]:
!nvidia-smi


Thu Jul 18 16:55:23 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Check to see is there access to CUDA with Pytorch

import torch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code. Only use GPU if available
#This is different than lecture where torch.device was not necessary
device = torch.device ("cuda" if torch.cuda.is_available() else "cpu")
print (device)

cuda


In [ ]:
# Count the number of devices
torch.cuda.device_count()

1

## Putting Tensors and models on the GPU

In [ ]:
#Create a tensor on default CPU location
tensor = torch.tensor([1,2,3])
tensor


tensor([1, 2, 3])

In [ ]:
print (tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Can explicitly declare the device
tensor = torch.tensor([1,2,3], device = "cpu")
print (tensor, tensor.device)

tensor([1, 2, 3]) cpu


####Pytorch makes it easy to move things to the target device

In [ ]:
#Move tensor to GPu (if available)  Device was set previously
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# Move tensor back to CPU. One case might be to use Numpy which only works on CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Remember how Python evaluates expressions. Right side first before doing assignment to left side. Right side starts left to righ evaulation of each expression.

In [ ]:
#Tensor on gpu remains unchanged because we assigned the move to another variable

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###EXERCISES

In [2]:
#Create a random tensor with shape (7, 7)
import torch
tensor = torch.rand(7,7)
tensor

tensor([[0.0264, 0.3159, 0.1435, 0.4776, 0.2905, 0.2376, 0.7244],
        [0.2979, 0.5512, 0.9779, 0.1418, 0.7127, 0.8932, 0.8098],
        [0.0754, 0.3610, 0.2667, 0.7558, 0.8656, 0.3825, 0.5830],
        [0.5432, 0.0914, 0.4698, 0.3406, 0.0611, 0.8426, 0.9498],
        [0.7671, 0.4162, 0.6803, 0.9652, 0.8703, 0.0574, 0.9399],
        [0.9266, 0.8202, 0.6262, 0.7057, 0.9159, 0.3902, 0.1827],
        [0.0320, 0.8760, 0.2381, 0.6085, 0.8314, 0.1224, 0.1656]])

In [ ]:
#perform a matrix multiplication with a tensor (1,7)
tensor_2 = torch.rand(1,7)
tensor_2
#transpose tensor_2 to perform matrix multiplication
tensor_2.T
# matmul the two tensors
torch.matmul(tensor, tensor_2.T)

tensor([[1.0413],
        [2.1746],
        [2.1708],
        [1.7823],
        [2.4514],
        [1.0398],
        [1.4459]])

In [ ]:
#Redo the operations above with both tensors with a random seed of 0
RANDOM_SEED =0
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)
RANDOM_SEED =0
torch.manual_seed(RANDOM_SEED)
tensor_2 = torch.rand(1,7)
tensor_matmul = torch.matmul(tensor, tensor_2.T)
tensor, tensor_2, tensor_matmul

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]))

In [ ]:
#The way to generate a tensor with a random seed in cuda is using tensor.cuda.seed()

torch.cuda.seed()
torch.cuda.manual_seed(1234)
torch.cuda.manual_seed_all(1234)

tensor = torch.rand(7,7)
tensor


tensor([[0.4217, 0.7315, 0.4991, 0.6040, 0.3479, 0.6605, 0.5150],
        [0.0926, 0.3143, 0.3407, 0.8237, 0.5030, 0.0737, 0.9511],
        [0.4361, 0.8462, 0.6765, 0.8241, 0.0958, 0.0934, 0.8564],
        [0.0202, 0.6226, 0.2212, 0.5231, 0.1306, 0.1090, 0.6834],
        [0.8427, 0.9358, 0.7290, 0.5327, 0.4475, 0.3022, 0.6237],
        [0.1663, 0.5176, 0.3337, 0.8030, 0.1932, 0.1285, 0.1669],
        [0.4845, 0.4987, 0.3760, 0.5112, 0.5570, 0.6459, 0.6014]])

In [1]:
# Create 2 random tensors and send them to the GPU
import torch
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)
print("Tensors A & B with OUT Seed:", tensor_A,tensor_B)

torch.cuda.manual_seed(1234)
tensor_A = torch.cuda.rand(2,3)
torch.cuda.manual_seed(1234)
tensor_B = torch.cuda.rand(2,3)
print("Tensors A & B with Seed:",tensor_A,tensor_B)
tensor_B = tensor_B.T
print(" Tensors A & B Transpose ", tensor_A,tensor_B)
tensor_A = tensor_A.to("cuda")
tensor_B = tensor_B.to("cuda")
tensor_A, tensor_B
%time
tensor_C = torch.matmul(tensor_A, tensor_B)
tensor_C

Tensors A & B with OUT Seed: tensor([[0.4621, 0.6778, 0.6961],
        [0.9704, 0.2981, 0.2224]]) tensor([[0.1479, 0.2662, 0.6533],
        [0.0544, 0.3876, 0.0099]])


AttributeError: module 'torch.cuda' has no attribute 'rand'

In [3]:
#Create 2 Random ensors with a Manual Seed directly on GPU

torch.cuda.manual_seed(1234)
tensor_on_GPU = torch.rand((2,3), device ="cuda")
print ("Tensor_on_GPU: \n",tensor_on_GPU)
torch.cuda.manual_seed(1234)
tensor_2_on_GPU = torch.rand((2,3), device ="cuda")
print ("Tensor_2_on_GPU: \n",tensor_2_on_GPU)



Tensor_on_GPU: 
 tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
Tensor_2_on_GPU: 
 tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')


In [6]:
# Transpose the second tensor so the dimensions are as required for Matmul

torch.cuda.manual_seed(1234)
tensor_on_GPU = torch.rand((2,3), device ="cuda")
print ("Tensor_on_GPU: \n",tensor_on_GPU)
torch.cuda.manual_seed(1234)
tensor_2_on_GPU = torch.rand((2,3), device ="cuda")
print ("Tensor_2_on_GPU: \n",tensor_2_on_GPU)
tensor_2_on_GPU = tensor_2_on_GPU.T
print ("Tensor_2_on_GPU Transposed: \n",tensor_2_on_GPU)
tensor_AxBT = torch.matmul(tensor_on_GPU, tensor_2_on_GPU)
print ("Tensor_AxBT: \n",tensor_AxBT)


Tensor_on_GPU: 
 tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
Tensor_2_on_GPU: 
 tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
Tensor_2_on_GPU Transposed: 
 tensor([[0.1272, 0.6601],
        [0.8167, 0.2721],
        [0.5440, 0.9737]], device='cuda:0')
Tensor_AxBT: 
 tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')


In [21]:
# Find the max and min of Tensor_AxBT
Tensor_max = torch.max(tensor_AxBT)
Tensor_min = torch.min(tensor_AxBT)
Tensor_max, Tensor_min
#Find the index of max and min
tensor_max_index = torch.argmax(tensor_AxBT)
tensor_min_index = torch.argmin(tensor_AxBT)
print(f"max of AxBT at index = {tensor_max_index} \n\
min of AxBT at index = {tensor_min_index}")

max of AxBT at index = 3 
min of AxBT at index = 1


In [26]:
#Make a random tensor with shape (1, 1, 1, 10) and
#then create a new tensor with all the 1 dimensions removed
#to be left with a tensor of shape (10). Set the seed to 7 when you create it
#and print out the first tensor
#and it's shape as well as the second tensor and it's shape.

RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(1,1,1,10)
print("tensor \n", tensor,"\n tensor shape is \n", tensor.shape)
tensor_1D = torch.squeeze(tensor)
tensor_1D, tensor_1D.shape

tensor 
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) 
 tensor shape is 
 torch.Size([1, 1, 1, 10])


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))