<a href="https://colab.research.google.com/github/77jackm/Bourke-Pytorch-Tutorial/blob/main/Copy_of_00_MyPyTorch_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

print ("This is my Pytorch Tutorial")

2.3.0+cu121
This is my Pytorch Tutorial


###Introduction to Tensors
Creating Tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get Python Tensor value back as an Int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# The number of dimensions of a tensor can be determined by inspection.
# Just look at the number of square bracket [] it has
vector.ndim

1

In [ ]:
# The item() method returns a single int value. Since a vector
# has 2 values you need to select which item in the vector
vector[1].item()

7

In [ ]:
vector.tolist()
vector.shape

[7, 7]

In [ ]:
# Find the shape of the vector.
# Shape indicates the number of dimensions and the number of elements in each dimension
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX  = torch.tensor([[7,8],
                        [8,9],
                        [10,11]])
MATRIX

tensor([[ 7,  8],
        [ 8,  9],
        [10, 11]])

In [ ]:
MATRIX.ndim

2

In [ ]:

MATRIX.shape

torch.Size([3, 2])

In [ ]:
# MATRIX
MATRIX  = torch.tensor([[[7,8],
                        [8,9]],
                        [[10,11],
                         [12,13]]])
MATRIX

tensor([[[ 7,  8],
         [ 8,  9]],

        [[10, 11],
         [12, 13]]])

In [ ]:
MATRIX.ndim


3

In [ ]:
MATRIX.shape

torch.Size([2, 2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                       ]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
TENSOR[0,0,1]

tensor(2)

In [3]:
#PRACTICE

#Create a tensor or order (2,3,5)

TENSOR1 = torch.tensor([[[0,1,2,3,4],
                         [5,6,7,8,9],
                         [10,11,12,13,14]],
                        [[15,16,17,18,19],
                         [20,21,22,23,24],
                         [25,26,27,28,29]]])
TENSOR1

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

In [4]:
TENSOR1.ndim

3

In [5]:
TENSOR1.shape

torch.Size([2, 3, 5])

In [9]:
TENSOR1[1,0,2].item()


17

In [12]:
TENSOR1[1,0,]

tensor([15, 16, 17, 18, 19])

In [19]:
# How to print each element of a tensor. Start with highest dimension and go down the hierarchy
for plane in TENSOR1:
  for row in plane:
    for column_element in row:
      print (column_element)

tensor(0)
tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)
tensor(10)
tensor(11)
tensor(12)
tensor(13)
tensor(14)
tensor(15)
tensor(16)
tensor(17)
tensor(18)
tensor(19)
tensor(20)
tensor(21)
tensor(22)
tensor(23)
tensor(24)
tensor(25)
tensor(26)
tensor(27)
tensor(28)
tensor(29)


In [26]:
#Float32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #Tensor datatype
                               device=None, #Device then tensor is on cpu or gpu
                               requires_grad=False) #Whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype


torch.float32

The 3 common error with PyTorch and ML
1. Using the wrong datatype or mixed datatypes
2. Tensors not the right shape (ie. Matrix Multiplication requires compatible shapes)
3. Allocating the tensor to the wrong device. Tensors in an operation have to be on same device

In [28]:
#To change data type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
output_tensor = float_32_tensor * float_16_tensor
output_tensor.dtype

torch.float32

In [35]:
#Information we want to regularly get from our tensors
TENSOR1.dtype
TENSOR1.shape
TENSOR1.device


torch.int64

torch.Size([2, 3, 5])

device(type='cpu')

In [3]:
#Create a tensor with random elements
some_tensor = torch.rand(3,4)
some_tensor


tensor([[0.9839, 0.6343, 0.5182, 0.9815],
        [0.8008, 0.8768, 0.1616, 0.1061],
        [0.4010, 0.1090, 0.6921, 0.3937]])

In [5]:
# Find the details of the tensor created
some_tensor
print (f"some_tensor has datatype: {some_tensor.dtype}")
print (f"some_tensor has shape: {some_tensor.shape}")
print (f"some_tensor is on device: {some_tensor.device}")



tensor([[0.9839, 0.6343, 0.5182, 0.9815],
        [0.8008, 0.8768, 0.1616, 0.1061],
        [0.4010, 0.1090, 0.6921, 0.3937]])

some_tensor has datatype: torch.float32
some_tensor has shape: torch.Size([3, 4])
some_tensor is on device: cpu


### Manipulating Tensors (Tensor Operations)**

Tensor Operations Include:
* Addition
* Substraction
* Multiplication (Element Wise)
* Division
* Matrix multiplication

In [6]:
#Create a Tensor and add a scalar to each element
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [7]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [8]:
# Subtract 10 from a tensor
tensor - 10


tensor([-9, -8, -7])

In [9]:
#There are also built-in Torch functions for these operations

torch.mul(tensor, 10)


tensor([10, 20, 30])

### MATRIX MULTIPLICATION

There are two mail rules of performing matrix multiplication in NN and DL

1. Scalar Multiplication: Element-wise multiplication
2. Matrix Multiplication: DOT PRODUCT (The most common operation in ANN)

Two requirements have meet for Matrix Multiplication:
1. A x B = C
Dimensions of matrices are such that A = m x n.    B = n x p.     C = n x p
the inner dimension "n" must match
2. The resulting matrix has the shape (dimensions) of outer dimension m x p

We can use tensor.shape to ensure that rule #1 is satisfied

In [11]:
# Element-Wise Multiplication
print (tensor, "*", tensor)
print (f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [12]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

Let's have a gazer is Australian for lets have a look

In [14]:
#Let's do the matrix multiplication by hand and time it
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print (value)

tensor(14)
CPU times: user 3.34 ms, sys: 1.97 ms, total: 5.31 ms
Wall time: 6.09 ms


In [21]:
%%time
output = torch.matmul(tensor, tensor)
print (output)
# You can also use @ sign instead of matmul
tensor @ tensor

tensor(14)
CPU times: user 2.11 ms, sys: 971 µs, total: 3.08 ms
Wall time: 2.79 ms


tensor(14)

###Shapes for MAtrix Multiplication

In [14]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
#torch.mm( tensor_A, tensor_B) #torch.mm is the same as torch.matmul
n1 = tensor_A.shape
n2 = tensor_B.shape
if n1[0] != n2[1]:
  print("Error: The inner dimensions must match")
#



Error: The inner dimensions must match


In [20]:
# To fix the error in this case we can manipulate the shape of one tensor using transpose
# A transpose switches the axes or dimensions of a given tensor

tensor_B
tensor_B.T # transpose
torch.mm(tensor_A, tensor_B.T)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

tensor([[ 7,  8,  9],
        [10, 11, 12]])

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [22]:
#Now transpose first tensor to see if we get the same result: Absolutely not. You don't
#evn have to compute it just look at the outer dimensions to see the size of the output
#tensor which 2x2 instead of 3x3
torch.mm(tensor_A.T, tensor_B)


tensor([[ 76, 103],
        [100, 136]])

##Tensor Aggregation: Find the min, max, mean, sum, etc
Called aggregation because reducing a multiple dimensional tensor into a scalaraero

In [3]:
#Create a tensor with a range of 100 and step of 10
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [25]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [26]:
#Find the mean
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [27]:
#Let's see the datatype arange created
x.dtype

torch.int64

In [30]:
#It's double precision float and mean wants single precision float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [31]:
#Find the sum of a tensor
torch.sum(x), x.sum()
# Either style is fine


(tensor(450), tensor(450))

### Find the Positional Location where these Aggregates occur


In [35]:
#Find the location of the max using argmax,
#Useful in SoftMax Activation Function calculation
print (f"Max value of X is at index:",torch.argmax(x))
print (f"Max value of X is:",x[torch.argmax(x)])

Max value of X is at index: tensor(9)
Max value of X is: tensor(90)


In [34]:
#Find the location of min using argmin
print (f"Min value of X is at index:",torch.argmin(x))
print (f"Min value of X is:",x[torch.argmin(x)])

Min value of X is at index: tensor(0)
Min value of X is: tensor(0)


### Reshaping, Stacking, Squeezing and Unsqueezing Tensors
* Reshaping: Changes the dimensions (shape) of a tensor to new defined shape
* View: Return a view of an input tensor of certain shape but use the same memory as original tensor
* Stacking: Stack multiple tensors on top of each other in any dimension (vstack is a special function for vertical) or similar to vstack side-by-side (hstack)
* Squeeze:  Removes a dimension of "1" from a target tensor
* Unsqueeze: Adds a dimension of "1" to a target
* Permute: Returns a view of the input with dimensions permuted (swapped) in a specified manner

In [36]:
x = torch.arange(1,101,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [6]:
x = torch.arange(start = 1.,end = 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
# The initial tensor must have sufficient elements to create the reshaped tensor
x = torch.reshape(x, (9,1))
x

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [2]:
x = torch.arange(1,11,1)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
x = torch.reshape( x, (1,2,5))
x, x.shape

(tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]),
 torch.Size([1, 2, 5]))

In [9]:
#Change the view. Changing z changes x because they share the same memory
z = x.view(1,9)
z,  z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Z declared to be a view of X is a pointer to X tensor. So if Z is changed then X changes

In [11]:
z[:,0]= 0.5
z, x

(tensor([[0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000]]),
 tensor([0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000]))

### STACKING TENSORS


In [12]:
# Stack Tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000]])

In [13]:
#Stack Tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [2.0000, 2.0000, 2.0000, 2.0000],
        [3.0000, 3.0000, 3.0000, 3.0000],
        [4.0000, 4.0000, 4.0000, 4.0000],
        [5.0000, 5.0000, 5.0000, 5.0000],
        [6.0000, 6.0000, 6.0000, 6.0000],
        [7.0000, 7.0000, 7.0000, 7.0000],
        [8.0000, 8.0000, 8.0000, 8.0000],
        [9.0000, 9.0000, 9.0000, 9.0000]])

In [14]:
x_vstacked = torch.vstack([x,x,x,x])
x_vstacked

tensor([[0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000],
        [0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000]])

In [16]:
x_hstacked = torch.hstack([x,x,x,x])
x_hstacked

tensor([0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000,
        0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000,
        0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000,
        0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000, 9.0000])

In [19]:
x.shape
x.reshape(1,1,9)
x.shape


torch.Size([9])

tensor([[[0.5000, 2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.0000, 8.0000,
          9.0000]]])

torch.Size([9])

In [20]:
#Squeeze the tensor: remove all dimensions =1
x.squeeze().shape


torch.Size([9])

In [11]:
x = torch.squeeze(x)
x.shape
x

torch.Size([2, 5])

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [14]:
# Note how unsqueezing adds one dimention at the location specified in "dim"
x = torch.unsqueeze(x, dim =3)
x.shape, x

(torch.Size([1, 2, 5, 1]),
 tensor([[[[ 1],
           [ 2],
           [ 3],
           [ 4],
           [ 5]],
 
          [[ 6],
           [ 7],
           [ 8],
           [ 9],
           [10]]]]))

In [17]:
shape = (2,3,4,5) # 2 volumes, 3 planes ea, 4 rows, 5 colums
x = torch.rand(shape)
x

tensor([[[[0.5520, 0.6825, 0.7769, 0.9218, 0.5108],
          [0.2313, 0.7962, 0.3952, 0.3686, 0.0157],
          [0.0913, 0.7596, 0.5869, 0.1310, 0.8788],
          [0.6177, 0.3767, 0.5937, 0.4577, 0.0249]],

         [[0.2815, 0.6006, 0.3203, 0.7489, 0.8626],
          [0.1603, 0.5197, 0.9791, 0.5299, 0.3749],
          [0.3845, 0.2587, 0.3284, 0.5820, 0.2596],
          [0.0058, 0.1046, 0.2394, 0.2081, 0.4300]],

         [[0.2086, 0.7971, 0.0532, 0.0953, 0.7196],
          [0.8831, 0.4754, 0.6267, 0.7833, 0.1276],
          [0.3537, 0.5724, 0.9079, 0.4654, 0.0278],
          [0.0173, 0.3268, 0.2477, 0.4142, 0.6079]]],


        [[[0.2447, 0.1266, 0.6585, 0.3272, 0.3346],
          [0.5679, 0.8273, 0.6012, 0.6810, 0.7612],
          [0.8438, 0.3448, 0.4627, 0.3317, 0.5930],
          [0.8932, 0.1139, 0.5700, 0.4343, 0.1535]],

         [[0.5632, 0.4756, 0.3516, 0.7186, 0.8335],
          [0.3127, 0.2278, 0.3127, 0.0260, 0.8612],
          [0.0023, 0.3677, 0.2028, 0.8438, 0.0896],
  

In [19]:
y = torch.randint(0,10,shape)
y, shape

(tensor([[[[4, 0, 2, 3, 3],
           [0, 5, 0, 9, 6],
           [5, 6, 9, 3, 4],
           [1, 9, 7, 1, 3]],
 
          [[1, 6, 4, 9, 7],
           [6, 3, 4, 4, 5],
           [0, 6, 5, 4, 2],
           [6, 9, 9, 1, 4]],
 
          [[5, 6, 3, 3, 5],
           [0, 7, 5, 9, 0],
           [7, 6, 9, 0, 9],
           [6, 2, 2, 6, 2]]],
 
 
         [[[5, 7, 4, 8, 8],
           [3, 6, 3, 0, 8],
           [9, 7, 9, 7, 7],
           [7, 1, 9, 7, 3]],
 
          [[2, 0, 9, 5, 7],
           [9, 3, 8, 8, 1],
           [3, 8, 2, 8, 7],
           [7, 4, 5, 4, 9]],
 
          [[4, 4, 2, 4, 9],
           [1, 4, 6, 9, 6],
           [9, 9, 1, 4, 5],
           [5, 7, 8, 3, 4]]]]),
 (2, 3, 4, 5))

### PERMUTING TENSORS

Permutting rearranges the elements of a tensor to the dimensions of the permutation requestes i.e. size(2,3,5) to size(5,2,3)
The input is the new order of dimensions i.e. (0,1,2) to (2,0,1). A permute is a view
Permutations of tensors are used often in Image Processing (Computer Vision)

In [8]:
x = torch.randn(2,3,5)
x.shape, x
x= torch.permute(x, (2,0,1))
x.shape, x

(torch.Size([2, 3, 5]),
 tensor([[[-1.7659,  0.3218, -1.3755, -0.8567,  1.8455],
          [ 0.4126,  0.1700, -0.5447,  2.1054,  0.5803],
          [ 0.0791, -0.5101, -2.1290,  1.8234,  0.8956]],
 
         [[ 0.2142,  0.6879,  1.7817, -1.3025,  1.3441],
          [ 0.4300,  0.1203, -0.5078, -0.0806, -1.2784],
          [-0.3381,  1.0017, -1.5547,  0.3098, -0.2481]]]))

(torch.Size([5, 2, 3]),
 tensor([[[-1.7659,  0.4126,  0.0791],
          [ 0.2142,  0.4300, -0.3381]],
 
         [[ 0.3218,  0.1700, -0.5101],
          [ 0.6879,  0.1203,  1.0017]],
 
         [[-1.3755, -0.5447, -2.1290],
          [ 1.7817, -0.5078, -1.5547]],
 
         [[-0.8567,  2.1054,  1.8234],
          [-1.3025, -0.0806,  0.3098]],
 
         [[ 1.8455,  0.5803,  0.8956],
          [ 1.3441, -1.2784, -0.2481]]]))